spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: movie-catalog-service
          uri: lb://movie-catalog-service
          predicates:
            - Path=/catalog/**
        - id: movie-info-service
          uri: lb://movie-info-service
          predicates:
            - Path=/movies/**
        - id: ratings-data-service
          uri: lb://ratings-data-service
          predicates:
            - Path=/ratingsdata/**


server:
  port: 9099

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://172.17.0.3:8761/eureka/
    instance:
        hostname: discovery-server