spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MOVIE-CATALOG-SERVICE
          uri: lb://MOVIE-CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
        - id: MOVIE-INFO-SERVICE
          uri: lb://MOVIE-INFO-SERVICE
          predicates:
            - Path=/movies/**
        - id: RATINGS-DATA-SERVICE
          uri: lb://RATINGS-DATA-SERVICE
          predicates:
            - Path=/ratingsdata/**


server:
  port: 9098

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.3:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"