spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MOVIE-CATALOG-SERVICE
          uri: lb://MOVIE-CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
        - id: MOVIE-INFO-SERVICE
          uri: lb://MOVIE-INFO-SERVICE
          predicates:
            - Path=/movies/**
        - id: RATINGS-DATA-SERVICE
          uri: lb://RATINGS-DATA-SERVICE
          predicates:
            - Path=/ratingsdata/**


server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service-svc:8761}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"